GET http://localhost:3000/api/machines HTTP/1.1


###
POST http://localhost:3000/api/machines HTTP/1.1
Content-Type: application/json

{
  "machine_type": "60a55c96abea3e3809953316",
  "status": "Damaged",
  "serial": "NOT AVAILABlE",
  "details": "Obsolete blue bailarine",
  "prize": "9"
}